
insert into Employe (NumEmp, Nom, Mail, DN) values (1, 'Murry Chatenet',   '9/27/1976');
insert into Employe (NumEmp, Nom, Mail, DN) values (2, 'Hortense Mangenot',   '1/30/1989');
insert into Employe (NumEmp, Nom, Mail, DN) values (3, 'Tatiania Portal',   '7/26/1989');
insert into Employe (NumEmp, Nom, Mail, DN) values (4, 'Janaye Ornelas',   '11/5/1985');
insert into Employe (NumEmp, Nom, Mail, DN) values (5, 'Garald Mish',   '2/2/1981');
insert into Employe (NumEmp, Nom, Mail, DN) values (6, 'Stoddard Phalp',   '12/19/1975');
insert into Employe (NumEmp, Nom, Mail, DN) values (7, 'Valentina Brickstock',   '12/23/1978');
insert into Employe (NumEmp, Nom, Mail, DN) values (8, 'Kathleen Melluish',   '6/12/1975');
insert into Employe (NumEmp, Nom, Mail, DN) values (9, 'Sherie Astill',   '9/20/1981');
insert into Employe (NumEmp, Nom, Mail, DN) values (10, 'Justis Perton',   '11/3/1983');
insert into Employe (NumEmp, Nom, Mail, DN) values (11, 'Waylen Kellough',   '9/13/1980');
insert into Employe (NumEmp, Nom, Mail, DN) values (12, 'Flint Smeaton',   '5/14/1980');
insert into Employe (NumEmp, Nom, Mail, DN) values (13, 'Saloma Corssen',   '7/30/1986');
insert into Employe (NumEmp, Nom, Mail, DN) values (14, 'Celle Serfati',   '11/24/1981');
insert into Employe (NumEmp, Nom, Mail, DN) values (15, 'Wat Spellessy',   '5/8/1976');
insert into Employe (NumEmp, Nom, Mail, DN) values (16, 'Niven Oboy',   '10/23/1983');
insert into Employe (NumEmp, Nom, Mail, DN) values (17, 'Wilburt Vicioso',   '1/21/1988');
insert into Employe (NumEmp, Nom, Mail, DN) values (18, 'Eden Hissie',   '8/26/1988');
insert into Employe (NumEmp, Nom, Mail, DN) values (19, 'Drew Ashard',   '9/20/1988');
insert into Employe (NumEmp, Nom, Mail, DN) values (20, 'Joyce Feake',   '7/26/1982');
insert into Employe (NumEmp, Nom, Mail, DN) values (21, 'Fayre Haslehurst',   '2/6/1981');
insert into Employe (NumEmp, Nom, Mail, DN) values (22, 'Melli Southerell',   '7/4/1987');
insert into Employe (NumEmp, Nom, Mail, DN) values (23, 'Hewie Le Brun',   '11/24/1983');
insert into Employe (NumEmp, Nom, Mail, DN) values (24, 'Maurizio Slinn',   '12/11/1980');
insert into Employe (NumEmp, Nom, Mail, DN) values (25, 'Cassy Sewley',   '11/6/1976');
insert into Employe (NumEmp, Nom, Mail, DN) values (26, 'Natal Callam',   '1/16/1978');
insert into Employe (NumEmp, Nom, Mail, DN) values (27, 'Harbert Muirhead',   '10/31/1981');
insert into Employe (NumEmp, Nom, Mail, DN) values (28, 'Gunar McVie',   '2/9/1977');
insert into Employe (NumEmp, Nom, Mail, DN) values (29, 'Lotta Stanning',   '2/27/1989');
insert into Employe (NumEmp, Nom, Mail, DN) values (30, 'Sorcha Gapp',   '11/9/1978');
--'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',
