insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (1, 'Transcof', 93, 1);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (2, 'Kanlam', 57, 2);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (3, 'Flowdesk', 122, 3);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (4, 'Fintone', 102, 4);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (5, 'Alphazap', 96, 5);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (6, 'It', 150, 6);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (7, 'Kanlam', 69, 7);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (8, 'Domainer', 73, 8);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (9, 'Rank', 121, 9);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (10, 'Matsoft', 121, 10);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (11, 'Home Ing', 131, 1);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (12, 'Sonair', 74, 2);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (13, 'Zathin', 112, 3);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (14, 'Viva', 79, 4);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (15, 'Span', 53, 5);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (16, 'Gembucket', 79, 6);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (17, 'Fix San', 131, 7);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (18, 'Hatity', 148, 8);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (19, 'Solarbreeze', 126, 9);
insert into Projet (NumProjet, NomProjet, Budget, NumDept) values (20, 'Greenlam', 116, 10);
